### ISSUE TITLE
LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)

### ISSUE THREAD

**Issue by catalin88** [vinsol-spree-contrib/spree-admin-insights#28]
I get this error while trying to install the 3-1-stable branch:

`/usr/local/rvm/gems/ruby-2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in require': LoadError: cannot load such file -- sequel/adapters/sqlite3 (Sequel::AdapterNotFound)`

Any ideas ?

**Comment by AnuragBhardwaj1** [comment]
@catalin88 
I think the error here is due to different adapter names for sqlite.
Sequel -> uses 'sqlite' as :adapter
sqlite gem -> uses 'sqlite3' as :adapter

as a solution we can modify params while connecting with Sequel in after_initialize.

**Comment by dsawa** [comment]
Nice, looking forward to see your fix merged.

**Comment by AnuragBhardwaj1** [comment]
@catalin88 
Is this PR solves your issue ?

**Comment by dsawa** [comment]
@AnuragBhardwaj1 
While @catalin88 is missing, I can confirm that this fixed same issue for me.

**Comment by AnuragBhardwaj1** [comment]
Thanks @catalin88 for the feedback.
Closing issue.
